<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Admin | 3GFood</title>
    @vite(['resources/css/app.css'])
    <style>
        .login-page{min-height:100vh;display:grid;grid-template-columns:1.05fr .95fr;background:#fbfaf7}.login-visual{padding:70px;display:flex;flex-direction:column;justify-content:space-between;background:#c45118;color:#fff}.login-visual h1{max-width:440px;font:800 56px/1.05 'Playfair Display',serif}.login-visual p{max-width:360px;line-height:1.7;color:#ffe4d4}.login-plate{width:260px;height:260px;object-fit:cover;border-radius:50%;border:12px solid rgba(255,255,255,.2);align-self:flex-end}.login-form-wrap{display:grid;place-items:center;padding:30px}.login-box{width:min(100%,410px)}.login-brand{color:#c45118;font:800 25px 'Playfair Display',serif;margin-bottom:65px}.login-brand strong{color:#29251f}.login-box h2{font:800 38px 'Playfair Display',serif;margin:0 0 10px}.login-box>p{color:#887f72;margin-bottom:32px}.login-box label{display:block;font-weight:700;margin:18px 0 0}.login-box input{display:block;width:100%;margin-top:8px;padding:13px;border:1px solid #e9e2d8;border-radius:8px}.login-box button{width:100%;margin-top:26px;padding:14px;border:0;border-radius:8px;color:#fff;background:#c45118;font-weight:700}.login-error{color:#b42318;font-size:13px;margin:12px 0}.remember{font-weight:400!important;font-size:13px}.remember input{display:inline-block;width:auto;margin:0 7px 0 0}@media(max-width:700px){.login-page{display:block}.login-visual{display:none}.login-form-wrap{min-height:100vh}.login-brand{margin-bottom:55px}}
    </style>
</head>
<body><main class="login-page"><section class="login-visual"><div><div class="login-brand" style="color:#fff">3G<strong style="color:#fff">Food</strong></div><h1>Kelola pesanan dengan lebih mudah.</h1><p>Pantau pesanan, pembayaran, dan pelanggan 3GFood dari satu tempat.</p></div><img class="login-plate" src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=85" alt="Hidangan 3GFood"></section><section class="login-form-wrap"><div class="login-box"><div class="login-brand">3G<strong>Food</strong></div><h2>Selamat datang.</h2><p>Masuk ke dashboard admin untuk melanjutkan.</p>@if($errors->any())<div class="login-error">{{ $errors->first() }}</div>@endif<form method="POST" action="{{ route('admin.login.submit') }}">@csrf<label for="email">Email<input id="email" name="email" type="email" value="{{ old('email') }}" placeholder="admin@3gfood.test" required autofocus></label><label for="password">Password<input id="password" name="password" type="password" placeholder="Masukkan password" required></label><label class="remember"><input type="checkbox" name="remember"> Ingat saya</label><button type="submit">Masuk ke Dashboard</button></form></div></section></main></body></html>
